:sentiments:
  achieve:
  affect:
  anger:
  anx:
  article:
  assent:
  body:
  cause:
  certain:
  cogmech:
  comm:
  death:
  discrep:
  down:
  eating:
  excl:
  family:
  feel:
  fillers:
  friends:
  future:
  groom:
  hear:
  home:
  humans:
  i:
  incl:
  inhib:
  insight:
  job:
  leisure:
  metaph:
  money:
  motion:
  music:
  negate:
  negemo:
  nonfl:
  number:
  occup:
  optim:
  other:
  otherf:
  past:
  physical:
  posemo:
  posfeel:
  preps:
  present:
  pronoun:
  relig:
  sad:
  school:
  see:
  self:
  senses:
  sexual:
  sleep:
  social:
  space:
  sports:
  swear:
  tv:
  tentat:
  time:
  up:
  we:
  you:
  gi_neg:
  gi_pos:








	



